{
 "title": "Containers",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Pod", "query": ".+" },
   { "name": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (namespace, pod) (rate(container_cpu_usage_seconds_total{pod=~\"^$Pod\",namespace=~\"$Namespace\"}[$__range])) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg by (namespace, pod) (container_memory_usage_bytes{pod=~\"^$Pod\",namespace=~\"$Namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network rx/tx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, namespace) (avg by (pod, namespace, interface) (rate(container_network_receive_bytes_total{pod=~\"$Pod\",namespace=~\"$Namespace\"}[$__range])))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "-sum by (pod, namespace) (avg by (pod, namespace, interface) (rate(container_network_transmit_bytes_total{pod=~\"$Pod\",namespace=~\"$Namespace\"}[$__range])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod, namespace) (avg by (pod, namespace, device) (rate(container_fs_writes_bytes_total{pod=~\"^$Pod\",namespace=~\"$Namespace\"}[$__range])))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "-sum by (pod, namespace) (avg by (pod, namespace, device) (rate(container_fs_reads_bytes_total{pod=~\"^$Pod\",namespace=~\"$Namespace\"}[$__range])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Restart",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{pod=~\"$Pod\",namespace=~\"$Namespace\"}[$__range])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Status_Not_Ready",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - avg by (pod, namespace) (kube_pod_container_status_ready{pod=~\"$Pod\",namespace=~\"$Namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scaling Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(kube_statefulset_status_replicas_ready{statefulset=~\"$Pod\",namespace=~\"$Namespace\"}, \"workload\", \"$1\", \"statefulset\", \"(.*)\")\r",
     "legendFormat": "{{workload}}"
    },
    {
     "expr": "label_replace(kube_deployment_status_replicas_available{deployment=~\"$Pod\",namespace=~\"$Namespace\"}, \"workload\", \"$1\", \"deployment\", \"(.*)\")\r",
     "legendFormat": "{{workload}}"
    },
    {
     "expr": "label_replace(kube_daemonset_status_number_available{daemonset=~\"$Pod\",namespace=~\"$Namespace\"}, \"workload\", \"$1\", \"daemonset\", \"(.*)\")\r",
     "legendFormat": "{{workload}}"
    }
   ]
  }
 ]
}