hello:
  image: kroniak/ssh-client:3.11 
  script:
    - mkdir /root/.ssh
    - cp ${PRI_KEY} /root/.ssh/id_rsa
    - cat /root/.ssh/id_rsa
    - chmod 400 /root/.ssh/id_rsa
    - ssh -o "StrictHostKeyChecking=no" benjah1@192.168.0.50 ls
  when: manual
