hello:
  image: kroniak/ssh-client:3.11 
  script:
    - eval $(ssh-agent -s)
    - cat ${PRI_KEY} | ssh-add -
    - ssh -o "StrictHostKeyChecking=no" benjah1@192.168.0.50 ls
    - |
      cat <<EOL | ssh -o "StrictHostKeyChecking=no" benjah1@192.168.0.50
      ls &&
      pwd
      EOL
    - pwd
    - ls
  when: manual
