01_vagrant_up:
  image: kroniak/ssh-client:3.11 
  script:
    - eval $(ssh-agent -s)
    - cat ${PRI_KEY} | ssh-add -
    - export PUB_KEY_VALUE=$(cat ${PUB_KEY})
    - ssh -o "StrictHostKeyChecking=no" benjah1@192.168.0.50 ls
    - scp -o "StrictHostKeyChecking=no" -r scripts benjah1@192.168.0.50:~/Documents
    - |
      cat <<EOL | ssh -o "StrictHostKeyChecking=no" -tt benjah1@192.168.0.50
      ls &&
      cd Documents &&
      if [ ! -d dotfiles ]; then git clone https://github.com/benjah1/dotfiles.git; fi &&
      if [ -d dotfiles ]; then pushd dotfiles; git pull; popd; fi &&
      bash ./scripts/vagrant_up.sh "${PUB_KEY_VALUE}" &&
      docker ps &&
      exit
      EOL
  when: manual

02_kind_up:
  image: kroniak/ssh-client:3.11 
  variables:
    REMOTE_HOST: 192.168.51.103
  script:
    - eval $(ssh-agent -s)
    - cat ${PRI_KEY} | ssh-add -
    - mkdir k8s-cluster/key
    - cp $K8S_CA_KEY k8s-cluster/key/ca.key
    - cp $K8S_CA_CRT k8s-cluster/key/ca.crt
    - scp -o "StrictHostKeyChecking=no" -r k8s-cluster vagrant@${REMOTE_HOST}:~/Documents
    - |
      cat <<EOL | ssh -o "StrictHostKeyChecking=no" -tt vagrant@${REMOTE_HOST}
      ls &&
      cd ~/Documents/k8s-cluster &&
      mkdir -p /home/vagrant/kind-data/pki &&
      if [ ! -f /home/vagrant/kind-data/pki/ca.key ]; then cp key/ca.key /home/vagrant/kind-data/pki/ca.key; fi &&
      if [ ! -f /home/vagrant/kind-data/pki/ca.crt ]; then cp key/ca.crt /home/vagrant/kind-data/pki/ca.crt; fi &&
      bash ./cluster_up.sh &&
      docker ps &&
      exit
      EOL
  when: manual
