kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."192.168.0.76:38081"]
    endpoint = ["http://192.168.0.76:38081"]
networking:
  disableDefaultCNI: true
  podSubnet: "10.244.0.0/16"
nodes:
- role: control-plane
  image: 192.168.0.76:38081/root/k8s-collection/kind-node:latest
  extraMounts:
  - hostPath: /home/vagrant/kind-data
    containerPath: /opt/kind-data
  - hostPath: /home/vagrant/kind-data/pki
    containerPath: /etc/kubernetes/pki
  extraPortMappings:
  - containerPort: 6443
    hostPort: 6443
    listenAddress: "0.0.0.0"
    protocol: TCP
- role: worker
  image: 192.168.0.76:38081/root/k8s-collection/kind-node:latest
  extraMounts:
  - hostPath: /home/vagrant/kind-data
    containerPath: /opt/kind-data
- role: worker
  image: 192.168.0.76:38081/root/k8s-collection/kind-node:latest
  extraMounts:
  - hostPath: /home/vagrant/kind-data
    containerPath: /opt/kind-data
- role: worker
  image: 192.168.0.76:38081/root/k8s-collection/kind-node:latest
  extraMounts:
  - hostPath: /home/vagrant/kind-data
    containerPath: /opt/kind-data
