{
 "title": "Node",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(node_load1,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Load Average 1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (node_load1{instance=~\"$Node\"}) /count by (instance) (node_cpu_seconds_total{instance=~\"$Node\",mode='system'})",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "CPU usage per 5m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_cpu_seconds_total{instance=~\"$Node\", mode=~\"user\"}[5m]) * 100",
     "legendFormat": " {{mode}} - {{cpu}} - {{instance}}"
    },
    {
     "expr": "-irate(node_cpu_seconds_total{instance=~\"$Node\", mode=~\"system\"}[5m]) * 100",
     "legendFormat": " {{mode}} - {{cpu}} - {{instance}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$Node\"}-node_memory_MemAvailable_bytes{instance=~\"$Node\"})/node_memory_MemTotal_bytes{instance=~\"$Node\"})*100",
     "legendFormat": "{{instance}} - used"
    },
    {
     "expr": "((node_memory_Cached_bytes{instance=~\"$Node\"} + node_memory_Buffers_bytes{instance=~\"$Node\"})/(node_memory_MemTotal_bytes{instance=~\"$Node\"})) * 100",
     "legendFormat": "{{instance}} - buffered"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "-sum by (instance) (irate(node_network_receive_bytes_total{instance=~'$Node'}[5m]))",
     "legendFormat": "rx - {{instance}}"
    },
    {
     "expr": "sum by (instance) (irate(node_network_transmit_bytes_total{instance=~'$Node'}[5m]))",
     "legendFormat": "tx - {{instance}}"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_read_bytes_total{instance=~\"$Node\"}[5m]))",
     "legendFormat": "read - {{instance}}"
    },
    {
     "expr": "- sum by (instance) (irate(node_disk_written_bytes_total{instance=~\"$Node\"}[5m]))",
     "legendFormat": "write - {{instance}}"
    }
   ]
  }
 ]
}