CREATE TABLE messages (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	msg_id VARCHAR(30) NOT NULL,
	message VARCHAR(50),
	create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

